name: Build AppImage

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - master # Make sure this is your main branch name

# Define a single job named 'build'
jobs:
  build:
    name: Build AppImage
    # Run on the latest Ubuntu Linux runner
    runs-on: ubuntu-latest

    # Steps to execute within the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install build dependencies via apt
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            automake \
            autoconf \
            intltool \
            pkg-config \
            gettext \
            libglib2.0-dev \
            libgtk-3-dev \
            libgtksourceview-3.0-dev \
            python3 \
            python3-pip \
            python3-gi \
            python3-gi-cairo \
            python3-xdg \
            fuse

      # Download linuxdeploy and its GTK plugin
      - name: Download linuxdeploy and plugins
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-gtk.sh
          sudo modprobe fuse || echo "fuse module already loaded or unavailable"
          mkdir -p $HOME/.cache/linuxdeploy

      # Create the m4 directory if it doesn't exist
      - name: Create m4 directory
        run: mkdir -p m4

      # Prepare build system (run autoreconf)
      - name: Prepare build system
        run: |
          autoreconf --force --install --verbose

      # Configure and Build
      - name: Configure and Build
        run: |
          ./configure --prefix=/usr
          make

      # Create the AppDir structure and install
      - name: Create AppDir and install
        run: |
          echo "--- Running make install ---"
          mkdir -p AppDir
          make install DESTDIR=$(pwd)/AppDir
          echo "--- Finished make install ---"
          echo "--- Listing AppDir/usr/bin ---"
          ls -l AppDir/usr/bin || echo "AppDir/usr/bin not found or empty"
          echo "--- Listing AppDir/usr/share/applications ---"
          ls -l AppDir/usr/share/applications || echo "AppDir/usr/share/applications not found or empty"
          echo "--- Listing AppDir/usr/share/icons ---"
          find AppDir/usr/share/icons -ls 2>/dev/null || echo "AppDir/usr/share/icons not found or empty"

      # Setup AppDir metadata (Fix categories, ensure icon, use printf fallback)
      - name: Setup AppDir metadata
        run: |
          DESKTOP_FILE="AppDir/usr/share/applications/desktop-entry-editor.desktop"
          # !!! DOUBLE-CHECK THIS PATH !!! Is this *exactly* where your icon is in the repo?
          ICON_SOURCE="data/icons/desktop-entry-editor.svg"
          ICON_DEST_DIR="AppDir/usr/share/icons/hicolor/scalable/apps"
          ICON_DEST_FILE="$ICON_DEST_DIR/desktop-entry-editor.svg"

          echo "Attempting to use source icon path: $ICON_SOURCE"
          echo "Checking if source icon exists..."
          ls -l "$ICON_SOURCE" || echo "Source icon '$ICON_SOURCE' NOT FOUND at listed path!"

          # Check if the installed desktop file exists
          if [ -f "$DESKTOP_FILE" ]; then
            echo "Desktop file found at '$DESKTOP_FILE'. Checking categories..."
            sed -i 's/Categories=Accessories;/Categories=Utility;/g' "$DESKTOP_FILE"
            echo "Ensured 'Categories=Utility;' in existing file."
          else
            # Fallback: Create a basic desktop file using printf
            echo "Desktop file not found at '$DESKTOP_FILE'! Creating a basic one..."
            mkdir -p "$(dirname "$DESKTOP_FILE")"
            printf "%s\n" \
              "[Desktop Entry]" \
              "Type=Application" \
              "Name=Desktop Entry Editor" \
              "Exec=desktop-entry-editor" \
              "Icon=desktop-entry-editor" \
              "Categories=Utility;" \
              > "$DESKTOP_FILE"
            echo "Created basic $DESKTOP_FILE"
          fi

          # Ensure icon exists, copy if needed
          echo "Checking if destination icon '$ICON_DEST_FILE' exists..."
          if [ ! -f "$ICON_DEST_FILE" ]; then
             # Only try to copy if source exists
             if [ -f "$ICON_SOURCE" ]; then
               echo "Destination icon not found. Copying from '$ICON_SOURCE'..."
               mkdir -p "$ICON_DEST_DIR"
               cp "$ICON_SOURCE" "$ICON_DEST_FILE"
               echo "Copied '$ICON_SOURCE' to '$ICON_DEST_FILE'"
               ls -l "$ICON_DEST_FILE" # Verify copy
             else
               # Source doesn't exist - This is the likely cause of the linuxdeploy error
               echo "ERROR: Source icon '$ICON_SOURCE' not found. Cannot copy icon."
               echo "ERROR: linuxdeploy will likely fail because the icon specified in the .desktop file cannot be found."
             fi
          else
             echo "Destination icon '$ICON_DEST_FILE' already exists."
          fi

          # Debugging: Print final desktop file content
          echo "--- Final contents of $DESKTOP_FILE ---"
          cat "$DESKTOP_FILE" || echo "Could not cat $DESKTOP_FILE"
          echo "--- End of $DESKTOP_FILE ---"


      # Create the AppImage using linuxdeploy (CORRECTED STEP)
      - name: Create AppImage
        run: |
          export DEPLOY_GTK_VERSION=3
          # Add LINUXDEPLOY_DEBUG=1 for much more verbose output if needed
          # export LINUXDEPLOY_DEBUG=1
          echo "Running linuxdeploy..."
          # Ensure each line ending with \ has it as the VERY last character
          # Ensure the last line does NOT end with \
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --plugin gtk \
            --output appimage \
            --desktop-file "AppDir/usr/share/applications/desktop-entry-editor.desktop"

      # Upload the generated AppImage artifact
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-entry-editor-AppImage
          # Adjust if linuxdeploy names the file differently, e.g., based on AppDir/Name in .desktop
          path: ./*-x86_64.AppImage
