name: Build AppImage

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install build tools and GTK dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
            libgtk-3-dev librsvg2-dev libasound2-dev libgirepository1.0-dev patchelf wget

      # Build the project with Autotools into AppDir
      - name: Build with Autotools
        run: |
          set -e
          autoreconf -i
          ./configure --prefix=/usr
          make
          mkdir -p AppDir/usr
          make DESTDIR=$PWD/AppDir install

      # (Optional) Prepare AppDir: copy desktop file and icon if not already installed
      - name: Prepare AppDir (copy desktop file and icon)
        if: false
        run: |
          # These commands are placeholders; replace with your actual paths if needed.
          mkdir -p AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/128x128/apps
          cp your-app.desktop AppDir/usr/share/applications/
          cp your-app.png AppDir/usr/share/icons/hicolor/128x128/apps/

      # Download linuxdeploy and GTK plugin, then bundle the AppImage
      - name: Create AppImage with linuxdeploy
        run: |
          set -e
          wget -q -O linuxdeploy-plugin-gtk.sh \
            https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          wget -q -O linuxdeploy-x86_64.AppImage \
            https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage linuxdeploy-plugin-gtk.sh
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin gtk --output appimage

      # Upload the resulting AppImage as a workflow artifact
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.AppImage
          path: "*.AppImage"
