# .github/workflows/build-appimage.yml

name: Build AppImage

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ] # Or your default branch (e.g., master)

  # Triggers the workflow when a release is published
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use a supported LTS Ubuntu version
    runs-on: ubuntu-22.04

    steps:
      #----------------------------------------------
      # Checkout Code
      #----------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      #----------------------------------------------
      # Set up Build Environment (WITH libfuse2)
      #----------------------------------------------
      - name: Install Dependencies (including libfuse2)
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            git \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            intltool \
            gettext \
            python3 \
            python3-pip \
            python3-gi \
            python3-gi-cairo \
            gir1.2-gtk-3.0 \
            gir1.2-gtksource-3.0 \
            python3-xdg \
            libgtk-3-dev \
            libgtksourceview-3.0-dev \
            libglib2.0-dev \
            wget \
            libfuse2 # FUSE dependency for running AppImages

      #----------------------------------------------
      # Download Core AppImage Tools (Corrected Python Plugin URL)
      #----------------------------------------------
      - name: Install Core AppImage Tools (linuxdeploy + python plugin)
        run: |
          # Download main linuxdeploy tool
          wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -O linuxdeploy
          # Download Python plugin from the correct 'niess' repo
          wget -c -nv "https://github.com/niess/linuxdeploy-plugin-python/releases/download/continuous/linuxdeploy-plugin-python-x86_64.AppImage" -O linuxdeploy-plugin-python
          chmod +x linuxdeploy linuxdeploy-plugin-python

      #----------------------------------------------
      # Build Desktop Entry Editor
      #----------------------------------------------
      - name: Prepare Autotools
        run: |
          aclocal -I m4
          intltoolize --force --copy
          autoconf
          automake --add-missing --copy --force-missing

      - name: Configure Build
        run: |
          ./configure --prefix=/usr

      - name: Make Build
        run: |
          make

      #----------------------------------------------
      # Prepare AppDir
      #----------------------------------------------
      - name: Create AppDir and Install
        run: |
          make install DESTDIR=AppDir

      #----------------------------------------------
      # Bundle Dependencies (Python & GSettings)
      #----------------------------------------------
      - name: Bundle Python Environment
        env:
          APPDIR: ${{ github.workspace }}/AppDir
        run: |
          # Run the Python plugin AFTER core tools are downloaded
          ./linuxdeploy-plugin-python --appdir $APPDIR

      - name: Compile GSettings Schema
        run: |
          SCHEMA_DIR="AppDir/usr/share/glib-2.0/schemas"
          if [ -d "$SCHEMA_DIR" ]; then
             echo "Compiling GSettings schemas in $SCHEMA_DIR..."
             glib-compile-schemas "$SCHEMA_DIR/"
          else
             # This warning appeared before, let's check install step
             echo "Warning: GSettings schema directory not found at $SCHEMA_DIR. Checking installation..."
             ls -lR AppDir/usr/share/glib-2.0 || echo "AppDir/usr/share/glib-2.0 not found"
          fi

      #----------------------------------------------
      # Create AppImage (Download GTK Plugin Script)
      #----------------------------------------------
      - name: Determine AppImage Version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "APP_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi
          echo "AppImage Version set to: ${{ steps.version.outputs.APP_VERSION }}"

      - name: Bundle Libraries and Create AppImage (using GTK script plugin) # <-- Step Updated
        env:
          APPDIR: ${{ github.workspace }}/AppDir
          VERSION: ${{ steps.version.outputs.APP_VERSION }}
        run: |
          # Download the GTK Plugin SCRIPT
          echo "Downloading linuxdeploy-plugin-gtk script..."
          wget -c -nv "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh" -O linuxdeploy-plugin-gtk # <-- CORRECT URL for script
          chmod +x linuxdeploy-plugin-gtk # Make the script executable

          # Now run linuxdeploy - it will find and execute the script plugin
          echo "Running linuxdeploy with plugins..."
          ./linuxdeploy --appdir $APPDIR \
            --executable usr/bin/desktop-entry-editor \
            --desktop-file usr/share/applications/desktop-entry-editor.desktop \
            --icon-file usr/share/icons/hicolor/scalable/apps/desktop-entry-editor.svg \
            --plugin gtk \
            --output appimage

      #----------------------------------------------
      # Upload Artifacts
      #----------------------------------------------
      - name: Prepare Artifact Name
        id: artifact_info
        run: |
          ARTIFACT_FILENAME="Desktop-Entry-Editor-${{ steps.version.outputs.APP_VERSION }}-x86_64.AppImage"
          echo "FILENAME=$ARTIFACT_FILENAME" >> $GITHUB_OUTPUT
          GENERATED_APPIMAGE=$(find . -maxdepth 1 -name 'Desktop*.AppImage' -print -quit)
          if [[ -z "$GENERATED_APPIMAGE" ]]; then
            echo "::error::Could not find generated AppImage file!"
            exit 1
          fi
          echo "Found generated AppImage: $GENERATED_APPIMAGE"
          mv "$GENERATED_APPIMAGE" "$ARTIFACT_FILENAME"
          echo "Renamed to: $ARTIFACT_FILENAME"

      - name: Upload AppImage as Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-Entry-Editor-AppImage
          path: ${{ steps.artifact_info.outputs.FILENAME }}

      #----------------------------------------------
      # Upload to Release (Only if triggered by release)
      #----------------------------------------------
      - name: Upload AppImage to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.artifact_info.outputs.FILENAME }}
          asset_name: ${{ steps.artifact_info.outputs.FILENAME }}
          asset_content_type: application/vnd.appimage
