# .github/workflows/build-appimage.yml

name: Build AppImage

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # --- Checkout Code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Install Dependencies ---
      - name: Install Dependencies (including libfuse2)
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            git build-essential autoconf automake libtool pkg-config \
            intltool gettext python3 python3-pip python3-gi \
            python3-gi-cairo gir1.2-gtk-3.0 gir1.2-gtksource-3.0 \
            python3-xdg libgtk-3-dev libgtksourceview-3.0-dev \
            libglib2.0-dev wget libfuse2 desktop-file-utils # Keep desktop-file-utils just in case

      # --- Download Core AppImage Tools ---
      - name: Install Core AppImage Tools (linuxdeploy + python plugin)
        run: |
          wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -O linuxdeploy
          wget -c -nv "https://github.com/niess/linuxdeploy-plugin-python/releases/download/continuous/linuxdeploy-plugin-python-x86_64.AppImage" -O linuxdeploy-plugin-python
          chmod +x linuxdeploy linuxdeploy-plugin-python

      # --- Build Desktop Entry Editor ---
      - name: Prepare Autotools
        run: |
          aclocal -I m4
          intltoolize --force --copy
          autoconf
          automake --add-missing --copy --force-missing -v
      - name: Configure Build
        run: |
          ./configure --prefix=/usr
      - name: Make Build
        run: |
          make V=1

      # --- Set Execute Permissions ---  <- NEW STEP
      - name: Set Execute Permissions on Script
        run: |
          chmod +x src/desktop-entry-editor
          echo "Set execute permission on src/desktop-entry-editor"

      # --- VERIFY BUILD OUTPUTS ---
      - name: Verify Build Output Files
        run: |
          echo "--- Checking for files generated by 'make' in build directories ---"
          # Verify the main *script* exists and is executable
          ls -l src/desktop-entry-editor || { echo "::error::Executable script 'src/desktop-entry-editor' not found!"; exit 1; }
          [ -x src/desktop-entry-editor ] || { echo "::error::Script 'src/desktop-entry-editor' is not executable!"; exit 1; }
          # Verify other necessary files
          ls -l data/apps.desktop-entry-editor.gschema.xml || { echo "::error::Schema 'data/apps.desktop-entry-editor.gschema.xml' not found!"; exit 1; }
          ls -l data/desktop-entry-editor.desktop || { echo "::error::Desktop file 'data/desktop-entry-editor.desktop' not found!"; exit 1; }
          ls -l src/dee/__init__.py || { echo "::error::Python module __init__.py 'src/dee/__init__.py' not found!"; exit 1; }
          ls -l data/icons/hicolor/scalable/apps/desktop-entry-editor.svg || { echo "::error::Icon file 'data/icons/hicolor/scalable/apps/desktop-entry-editor.svg' not found!"; exit 1; }

          echo "Required build output files found and executable script verified."

      # --- Prepare AppDir for Bundling ---
      - name: Create AppDir Structure
        run: |
          mkdir -p AppDir # Create the base AppDir

      # --- Bundle Python Environment FIRST ---
      - name: Bundle Python Environment
        env:
          APPDIR: ${{ github.workspace }}/AppDir
          LINUXDEPLOY_PYTHON_EXECUTABLE: ${{ github.workspace }}/src/desktop-entry-editor
        run: |
          echo "Running linuxdeploy-plugin-python..."
          if [ ! -f "$LINUXDEPLOY_PYTHON_EXECUTABLE" ]; then
             echo "::error::Source executable script '$LINUXDEPLOY_PYTHON_EXECUTABLE' not found. Cannot run python plugin."
             exit 1
          fi
          if [ ! -d "${{ github.workspace }}/src/dee" ]; then
             echo "::error::Source python module directory '${{ github.workspace }}/src/dee' not found. Cannot run python plugin."
             exit 1
          fi

          ./linuxdeploy-plugin-python --appdir $APPDIR

          echo "--- Verifying contents after Python plugin ---"
          ls -l $APPDIR/AppRun || { echo "::error::AppRun script NOT found in AppDir after python plugin run!"; exit 1; }
          [ -x $APPDIR/AppRun ] || { echo "::error::AppRun script exists but is not executable!"; exit 1; }
          find AppDir -name "python*" -wholename "*/bin/python*" -ls || echo "::warning::Python interpreter not found in AppDir bin."
          find AppDir -wholename "*/site-packages/dee" -ls || echo "::warning::Python module 'dee' directory not found in AppDir site-packages."
          echo "Python plugin verification complete (check warnings)."


      # --- Determine AppImage Version ---
      - name: Determine AppImage Version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "APP_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            SHORT_HASH=$(git rev-parse --short HEAD)
            echo "APP_VERSION=${LATEST_TAG}+git${SHORT_HASH}" >> $GITHUB_OUTPUT
          fi
          echo "AppImage Version set to: ${{ steps.version.outputs.APP_VERSION }}"

      # --- Bundle Libraries and Create AppImage ---
      - name: Bundle Libraries and Create AppImage (using GTK plugin)
        env:
          APPDIR: ${{ github.workspace }}/AppDir
          VERSION: ${{ steps.version.outputs.APP_VERSION }}
          ARCH: x86_64
          OUTPUT: Desktop-Entry-Editor-${{ steps.version.outputs.APP_VERSION }}-${ARCH}.AppImage
        run: |
          echo "Downloading linuxdeploy-plugin-gtk script..."
          wget -c -nv "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh" -O linuxdeploy-plugin-gtk
          chmod +x linuxdeploy-plugin-gtk

          echo "Running main linuxdeploy command..."

          if [ ! -x "$APPDIR/AppRun" ]; then
            echo "::error::AppRun script missing or not executable in $APPDIR before running main linuxdeploy."
            exit 1
          fi
          if ! [ -f "data/desktop-entry-editor.desktop" ] || \
             ! [ -f "data/icons/hicolor/scalable/apps/desktop-entry-editor.svg" ] || \
             ! [ -f "data/apps.desktop-entry-editor.gschema.xml" ]; then
             echo "::error::Missing desktop/icon/schema file in build directory before linuxdeploy."
             exit 1
          fi

          ./linuxdeploy --appdir $APPDIR \
            --desktop-file data/desktop-entry-editor.desktop \
            --icon-file data/icons/hicolor/scalable/apps/desktop-entry-editor.svg \
            --deploy-deps-only data/apps.desktop-entry-editor.gschema.xml \
            --plugin gtk \
            --output appimage

          echo "--- Verifying contents after main linuxdeploy ---"
          find $APPDIR/usr/share/glib-2.0/schemas -name "gschemas.compiled" -ls || echo "::warning::gschemas.compiled NOT found. Gtk plugin might not have run correctly or schema wasn't found."
          ls -l "$OUTPUT" || { echo "::error::Expected AppImage file '$OUTPUT' not found after linuxdeploy!"; exit 1; }
          echo "Main linuxdeploy command finished."


      # --- Upload Artifacts ---
      - name: Set Artifact Path Output
        id: artifact_info
        run: |
          ARTIFACT_FILENAME="Desktop-Entry-Editor-${{ steps.version.outputs.APP_VERSION }}-x86_64.AppImage"
          echo "FILENAME=$ARTIFACT_FILENAME" >> $GITHUB_OUTPUT
          echo "Expected artifact path: ./$ARTIFACT_FILENAME"

      - name: Upload AppImage as Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-Entry-Editor-AppImage
          path: ${{ steps.artifact_info.outputs.FILENAME }}

      # --- Upload to Release ---
      - name: Upload AppImage to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.artifact_info.outputs.FILENAME }}
          asset_name: ${{ steps.artifact_info.outputs.FILENAME }}
          asset_content_type: application/vnd.appimage
